development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: railsagain_development
  pool: 5
  username: server
  password: 

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: railsagain_test
  pool: 5
  username: server
  password: 

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: railsagain_production
  pool: 5
  username: server
  password: 
